{ myvars, config, pkgs, nix-secrets, ...}: 
let
  secretsFile = "${nix-secrets}/modules/nixos/base/secrets.yaml";
in
{ 
  # Don't allow mutation of users outside the config.
  users.mutableUsers = false;

  users.groups = {
    "${myvars.root_username}" = {};
    docker = {};
    # misc
    uinput = {};
  };

  users.users."${myvars.root_username}" = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    home = "/home/${myvars.root_username}";
    isNormalUser = true;
    hashedPasswordFile = config.sops.secrets.user-password.path;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ7X82I2M5GWwCnXugSceeFn4sSUexcoth4aRkZLyzkz"
    ];
    #mkpasswd -m sha-512
    #https://github.com/NixOS/nixpkgs/issues/165858
    extraGroups = [
      myvars.root_username
      "users"
      "networkmanager"
      "wheel"
      "docker"
      #"libvirtd"
    ];
  };

  sops.secrets.user-password = {
      sopsFile = "${secretsFile}";
      neededForUsers = true;
    };

  # set user's default shell system-wide
  users.defaultUserShell = pkgs.zsh;
  
}
